import { z } from 'zod';
export declare const themeListItemSchema: z.ZodObject<{
    id: z.ZodString;
    slug: z.ZodString;
    level: z.ZodString;
    category: z.ZodString;
    title: z.ZodString;
    description: z.ZodString;
    estimatedMinutes: z.ZodNumber;
    difficulty: z.ZodNumber;
    purposeTags: z.ZodArray<z.ZodString, "many">;
    isActive: z.ZodBoolean;
}, "strip", z.ZodTypeAny, {
    id: string;
    description: string;
    title: string;
    slug: string;
    level: string;
    category: string;
    estimatedMinutes: number;
    difficulty: number;
    purposeTags: string[];
    isActive: boolean;
}, {
    id: string;
    description: string;
    title: string;
    slug: string;
    level: string;
    category: string;
    estimatedMinutes: number;
    difficulty: number;
    purposeTags: string[];
    isActive: boolean;
}>;
export declare const themeDetailSchema: z.ZodObject<{
    id: z.ZodString;
    slug: z.ZodString;
    level: z.ZodString;
    category: z.ZodString;
    title: z.ZodString;
    description: z.ZodString;
    estimatedMinutes: z.ZodNumber;
    difficulty: z.ZodNumber;
    purposeTags: z.ZodArray<z.ZodString, "many">;
    isActive: z.ZodBoolean;
} & {
    promptText: z.ZodString;
    explanationGoal: z.ZodString;
    recommendedModelId: z.ZodString;
    keywords: z.ZodArray<z.ZodString, "many">;
    usefulExpressions: z.ZodArray<z.ZodString, "many">;
    hints: z.ZodArray<z.ZodString, "many">;
    nextThemeId: z.ZodNullable<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id: string;
    description: string;
    title: string;
    slug: string;
    level: string;
    category: string;
    estimatedMinutes: number;
    difficulty: number;
    purposeTags: string[];
    isActive: boolean;
    promptText: string;
    explanationGoal: string;
    recommendedModelId: string;
    keywords: string[];
    usefulExpressions: string[];
    hints: string[];
    nextThemeId: string | null;
}, {
    id: string;
    description: string;
    title: string;
    slug: string;
    level: string;
    category: string;
    estimatedMinutes: number;
    difficulty: number;
    purposeTags: string[];
    isActive: boolean;
    promptText: string;
    explanationGoal: string;
    recommendedModelId: string;
    keywords: string[];
    usefulExpressions: string[];
    hints: string[];
    nextThemeId: string | null;
}>;
export declare const themeDetailResponseSchema: z.ZodObject<{
    theme: z.ZodObject<{
        id: z.ZodString;
        slug: z.ZodString;
        level: z.ZodString;
        category: z.ZodString;
        title: z.ZodString;
        description: z.ZodString;
        estimatedMinutes: z.ZodNumber;
        difficulty: z.ZodNumber;
        purposeTags: z.ZodArray<z.ZodString, "many">;
        isActive: z.ZodBoolean;
    } & {
        promptText: z.ZodString;
        explanationGoal: z.ZodString;
        recommendedModelId: z.ZodString;
        keywords: z.ZodArray<z.ZodString, "many">;
        usefulExpressions: z.ZodArray<z.ZodString, "many">;
        hints: z.ZodArray<z.ZodString, "many">;
        nextThemeId: z.ZodNullable<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        id: string;
        description: string;
        title: string;
        slug: string;
        level: string;
        category: string;
        estimatedMinutes: number;
        difficulty: number;
        purposeTags: string[];
        isActive: boolean;
        promptText: string;
        explanationGoal: string;
        recommendedModelId: string;
        keywords: string[];
        usefulExpressions: string[];
        hints: string[];
        nextThemeId: string | null;
    }, {
        id: string;
        description: string;
        title: string;
        slug: string;
        level: string;
        category: string;
        estimatedMinutes: number;
        difficulty: number;
        purposeTags: string[];
        isActive: boolean;
        promptText: string;
        explanationGoal: string;
        recommendedModelId: string;
        keywords: string[];
        usefulExpressions: string[];
        hints: string[];
        nextThemeId: string | null;
    }>;
    recommendedModel: z.ZodObject<{
        id: z.ZodString;
        slug: z.ZodEnum<["prep", "stepbystep", "scqa"]>;
        nameJa: z.ZodString;
        shortDescription: z.ZodString;
        longDescription: z.ZodString;
        structureLabel: z.ZodString;
        steps: z.ZodArray<z.ZodString, "many">;
        features: z.ZodArray<z.ZodString, "many">;
        suitableFor: z.ZodArray<z.ZodString, "many">;
    }, "strip", z.ZodTypeAny, {
        id: string;
        slug: "prep" | "stepbystep" | "scqa";
        nameJa: string;
        shortDescription: string;
        longDescription: string;
        structureLabel: string;
        steps: string[];
        features: string[];
        suitableFor: string[];
    }, {
        id: string;
        slug: "prep" | "stepbystep" | "scqa";
        nameJa: string;
        shortDescription: string;
        longDescription: string;
        structureLabel: string;
        steps: string[];
        features: string[];
        suitableFor: string[];
    }>;
}, "strip", z.ZodTypeAny, {
    theme: {
        id: string;
        description: string;
        title: string;
        slug: string;
        level: string;
        category: string;
        estimatedMinutes: number;
        difficulty: number;
        purposeTags: string[];
        isActive: boolean;
        promptText: string;
        explanationGoal: string;
        recommendedModelId: string;
        keywords: string[];
        usefulExpressions: string[];
        hints: string[];
        nextThemeId: string | null;
    };
    recommendedModel: {
        id: string;
        slug: "prep" | "stepbystep" | "scqa";
        nameJa: string;
        shortDescription: string;
        longDescription: string;
        structureLabel: string;
        steps: string[];
        features: string[];
        suitableFor: string[];
    };
}, {
    theme: {
        id: string;
        description: string;
        title: string;
        slug: string;
        level: string;
        category: string;
        estimatedMinutes: number;
        difficulty: number;
        purposeTags: string[];
        isActive: boolean;
        promptText: string;
        explanationGoal: string;
        recommendedModelId: string;
        keywords: string[];
        usefulExpressions: string[];
        hints: string[];
        nextThemeId: string | null;
    };
    recommendedModel: {
        id: string;
        slug: "prep" | "stepbystep" | "scqa";
        nameJa: string;
        shortDescription: string;
        longDescription: string;
        structureLabel: string;
        steps: string[];
        features: string[];
        suitableFor: string[];
    };
}>;
export type ThemeListItemDto = z.infer<typeof themeListItemSchema>;
export type ThemeDetailDto = z.infer<typeof themeDetailSchema>;
export type ThemeDetailResponseDto = z.infer<typeof themeDetailResponseSchema>;
